version: '3.8'

services:
  prosper-backend:
    build:
      context: .
      dockerfile: src/main/Dockerfile-backend
    ports:
      - "8080:8080"
    networks:
      - prosper-net

  prosper-frontend:
    build:
      context: .
      dockerfile: src/main/Dockerfile-frontend
    ports:
      - "80:80"
    networks:
      - prosper-net

networks:
  prosper-net:
    driver: bridge
