version: '3.8'

services:
  prosper-backend:
    build:
      context: .
      dockerfile: src/main/Dockerfile-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - prosper-net

  prosper-frontend:
    build:
      context: .
      dockerfile: src/main/Dockerfile-frontend
    ports:
      - "80:80"
    networks:
      - prosper-net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - prosper-net
    volumes:
      - prosper-mongo-data:/data/db

networks:
  prosper-net:
    driver: bridge

volumes:
  prosper-mongo-data:
