# MongoDB connection settings
spring.data.mongodb.uri=mongodb+srv://denifer:admin123@mongodb-demo.p1jch.mongodb.net/?retryWrites=true&w=majority&appName=mongodb-demo

# Optional: Specify the database name
spring.data.mongodb.database=prospers_llc

# Server settings
server.port=8080
