# MongoDB connection settings
spring.data.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.mongodb.net/prospers_llc?retryWrites=true&w=majority

# Optional: Specify the database name
spring.data.mongodb.database=prospers_llc

# Server settings
server.port=8080
