name: Build and Push Docker Image to Docker Hub

description: This GitHub Action builds a Docker image from the repository and pushes it to Docker Hub.

inputs:
  docker_username:
    description: 'Docker Hub username'
    required: true
    default: ''

  docker_password:
    description: 'Docker Hub password or token'
    required: true
    default: ''

  docker_image_name:
    description: 'Docker image name (e.g., username/repository-name)'
    required: true
    default: 'prosper-llc'

  docker_registry:
    description: 'Docker registry to push the image to (default is Docker Hub)'
    required: false
    default: 'docker.io'

  app_version:
    description: 'Docker image version tag (default is latest)'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: 'docker://docker:19.03.12'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ inputs.docker_registry }}/${{ inputs.docker_image_name }}:${{ inputs.app_version }} .

    - name: Push Docker Image
      run: |
        docker push ${{ inputs.docker_registry }}/${{ inputs.docker_image_name }}:${{ inputs.app_version }}

    - name: Logout from Docker Hub
      run: |
        docker logout ${{ inputs.docker_registry }}
