name: Prospers LLC CI Master

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Disable shallow clone to improve reporting

      # Set up JDK 17 (Temurin is the recommended distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Ensure we're using the right distribution (Temurin)

      # Cache Maven dependencies to speed up builds (Updated to use actions/cache@v3)
      - name: Cache Maven Dependencies
        uses: a
