name: Prospers LLC CI Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Disable shallow clone to improve reporting

      # Set up JDK 17 (Temurin is the recommended distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Ensure we're using the right distribution (Temurin)

      # Cache Maven dependencies to speed up builds (Updated to use actions/cache@v3)
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build with Maven (Run tests here)
      - name: Build with Maven
        run: mvn clean install

      # Login to Docker Hub for pushing images
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image with dynamic tag using Git commit SHA
      - name: Build Docker Image
        run: |
          
          docker build -t iscanprint/prospersllc:2.2 .

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push iscanprint/prospersllc:2.2

      # Logout from Docker Hub after pushing
      - name: Logout from Docker Hub
        run: docker logout
